# -*- coding: utf-8 -*-
"""AI_Assistant_for_University_Helpdesk.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B3QkHzpewtjM7P5gtgrFJS9Z970waQIP
"""

# Scenario-Based Assessment
# Case Study: AI Assistant for a University Helpdesk
# A large university receives thousands of student queries daily related to admissions, fees, hostel facilities, course
#  schedules, and exam results.
# Currently, these queries are answered manually by staff, causing:
# Slow response time
# High operational cost
# Inconsistent responses
# The university plans to develop an AI-powered chatbot using Generative AI and Large Language Models (LLMs) to
#  automatically respond to student questions.
# You are part of the AI consulting team tasked with designing the solution.
# ==========================================
# UNIVERSITY AI HELPDESK CHATBOT
# Demonstrates:
# Generative AI
# Large Language Models (LLMs)
# Tokenization
# Transformer Inference
# Prompt Engineering
# ==========================================
# Install required libraries first
# pip install transformers torch

# ADVANCED UNIVERSITY AI HELPDESK CHATBOT

# STEP 3: Define University Knowledge Base
# # ------------------------------------------
# knowledge_base = """
# University Helpdesk Information

# Hostel Admission Requirements:
# - Admission confirmation letter
# - Government ID proof
# - Two passport size photographs

# Course Registration:
# - Registration happens online through the university portal
# - Students must register before the semester deadline

# Fee Payment:
# - Fees can be paid through the student dashboard
# - Online payment methods include debit card, credit card, and net banking

# Examination Schedule:
# - Semester exams usually start in December and May

# Library Access:
# - Students must carry their university ID card
# """

# STEP 1: Install libraries
# !pip install transformers torch sentence-transformers

# STEP 2: Import libraries
from transformers import AutoModelForSeq2SeqLM, AutoTokenizer

# STEP 3: Load the FLAN-T5 model
model_name = "google/flan-t5-small"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSeq2SeqLM.from_pretrained(model_name)

# STEP 4: Define University Knowledge Base
knowledge_base = """
University Helpdesk Information:

Hostel Admission Requirements:
- Admission confirmation letter
- Government ID proof
- Two passport size photographs

Course Registration:
- Registration happens online through the university portal
- Students must register before the semester deadline

Fee Payment:
- Fees can be paid through the student dashboard
- Online payment methods include debit card, credit card, and net banking

Examination Schedule:
- Semester exams usually start in December and May

Library Access:
- Students must carry their university ID card
"""

# STEP 5: Helper function to generate AI response
def generate_response(student_question):
    prompt = f"""
You are a helpful university AI assistant.
Answer the student's question fully using the knowledge base below.

Knowledge Base:
{knowledge_base}

Student Question: {student_question}

Answer:
"""
    # Tokenize input
    inputs = tokenizer(prompt, return_tensors="pt", max_length=512, truncation=True)

    # Generate output
    outputs = model.generate(
        **inputs,
        max_new_tokens=250,
        num_beams=3,
        early_stopping=True
    )

    # Decode output
    answer = tokenizer.decode(outputs[0], skip_special_tokens=True)
    return answer

# STEP 6: Interactive student loop
print("Welcome to the Advanced University AI Helpdesk! Type 'exit' to quit.\n")

while True:
    student_question = input("Enter your question: ")

    if student_question.strip().lower() == "exit":
        print("Thank you for using the AI Helpdesk. Goodbye!")
        break

    answer = generate_response(student_question)
    print("\nAI Helpdesk Response:")
    print(answer)
    print("\n" + "-"*60 + "\n")